### ISSUE TITLE
Error building with varnish 6.4

### ISSUE THREAD

**Issue by nosage** [rezan/libvmod-jemalloc#2]
I did install libjemalloc-dev, and built/installed varnish-modules with no issues.  System is a docker image: debian:buster-slim.  I am doing:
```
	./autogen.sh; \
	./configure; \
	make;
```
here is the build log: https://gist.github.com/nosage/e57ffad2b0f4c8e1ba24a3ca70ccbc1d

`#  error "include vrt.h before vcl.h"`

I tried to change the order of the includes, and made other adjustments but just kept getting errors.  Maybe I am missing a dep or doing something else wrong.  I appreciate any help on this!

**Comment by rezan** [comment]
Yup, master was last updated for 4.0/4.1. Does not work with 6.0+. I can fix this next week.

**Comment by rezan** [comment]
I updated master. Tested with Varnish 6.0 and 6.5. Also tested with jemalloc 3.6 and 5.1. Please re-open is this does not work for you.
