### ISSUE TITLE
Deprecation with Varnish 6.5

### ISSUE THREAD

**Issue by BastienBalaud** [rezan/libvmod-jemalloc#3]
Hi,

I try to build the vmod on CentOS 8 with Varnish 6.5 but i encounter a deprecation that block the build. 
```
make
make  all-recursive
make[1]: Entering directory '/tmp/libvmod-jemalloc'
Making all in src
make[2]: Entering directory '/tmp/libvmod-jemalloc/src'
  CC       vmod_jemalloc.lo
vmod_jemalloc.c: In function 'vmod_get_stats':
vmod_jemalloc.c:50:2: error: 'VSB_new' is deprecated [-Werror=deprecated-declarations]
  VSB_new(&v, ctx->ws->f, available, VSB_AUTOEXTEND);
  ^~~~~~~
In file included from vmod_jemalloc.c:8:
/usr/include/varnish/vsb.h:62:13: note: declared here
 struct vsb *VSB_new(struct vsb *, char *, int, int) v_deprecated_;
             ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:669: vmod_jemalloc.lo] Error 1
make[2]: Leaving directory '/tmp/libvmod-jemalloc/src'
make[1]: *** [Makefile:495: all-recursive] Error 1
make[1]: Leaving directory '/tmp/libvmod-jemalloc'
make: *** [Makefile:406: all] Error 2
```
I found that the function VSB_new is deprecated in Varnish 6.5 (https://varnish-cache.org/docs/trunk/whats-new/changes-6.5.html#libvarnish) and i try to fix by myself without success.

**Comment by rezan** [comment]
I can take a look at this soon, looks like we need a new branch to cover this change.

**Comment by rezan** [comment]
I believe https://github.com/rezan/libvmod-jemalloc/commit/ea8045a5fad4009cc01ded04ead8674395744de3 should fix it. So just pull the latest `master`. Please re-open if you still run into a problem.
